name: ServerManager
main: org.mswsplex.servermanager.msws.ServerManager
version: 1.1.2
description: Server Management
softdepend:
- Multiverse-Core
commands:
  manage:
    usage: /<command>
    description: Main Test Command
    aliases:
    - test
    - mng
    - manageserver
  testworld:
    usage: /<command> <Type/WorldName>
    description: Create a test world or teleport to one
  confirm:
    usage: /<command>
    description: Confirms a pending command
  fill:
    usage: /<command>
    description: Vanilla MC Command but with better autotab
  gamerules:
    usage: /<command> <World>
    description: View all gamerules of the world
    aliases:
    - rules
    - grules
  forcefield:
    usage: /<command> <Size>
    description: Toggle forcefield
  enumerate:
    usage: /<command> [Player]
    aliases: en
  get:
    usage: /<command> [Item]